name: ASMR-67s

on:
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ─── escrever credenciais se existirem ──────────────────────────
      - name: Escrever credentials.json
        if: ${{ secrets.YOUTUBE_CRED_JSON != '' }}
        run: echo "${{ secrets.YOUTUBE_CRED_JSON }}" > credentials.json

      - name: Escrever token.json
        if: ${{ secrets.YOUTUBE_TOKEN_JSON != '' }}
        run: echo "${{ secrets.YOUTUBE_TOKEN_JSON }}" > token.json

      # ─── instalar ffmpeg (necessário para corte) ────────────────────
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # ─── gerar clipe (e tentar upload YouTube se token existir) ─────
      - name: Run ASMR bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/fetch_and_edit.py || true   # não falhar workflow

      # ─── copiar final.mp4 do /tmp para workspace ────────────────────
      - name: Copiar final.mp4 para o workspace
        run: |
          CLIP=$(find /tmp -name final.mp4 | head -n 1 || true)
          if [ -n "$CLIP" ]; then
            cp "$CLIP" "$GITHUB_WORKSPACE/final.mp4"
            echo "Clip copiado para $GITHUB_WORKSPACE/final.mp4"
          else
            echo "::warning ::Nenhum final.mp4 encontrado"
          fi

      # ─── publicar artefato (v4) ─────────────────────────────────────
      - name: Publicar artefato do clip
        uses: actions/upload-artifact@v4
        with:
          name: asmr-67s-clip
          path: final.mp4
          if-no-files-found: warn   # não quebra o job
